# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: "Install dependencies"
      run: yarn install
    - name: "Lint back-end"
      run: yarn lint
    - name: "Test back-end"
      run: yarn test
    - name: "Build back-end"
      run: yarn build
    - name: "Lint front-end"
      run: yarn lint:fe
    - name: "Test front-end"
      run: yarn test:fe
    - name: "Build front-end"
      run: yarn build:fe
